class IBKRMarketClient:
    def __init__(self, cfg): ...
    async def connect(self): ...
    async def subscribe_rt(self, contract, whatToShow): ...
    async def request_hist(self, contract, duration, barSize, whatToShow, useRTH): ...
    def health(self): return {"connected": True, "session": 'market'}
