"""
Order models for the 3-plane trading system.

Defines:
- OrderIntent: Pre-execution order specification (input to order plane)
- OrderExec: Post-execution order record (output from broker)
- OrderStatus: Order lifecycle states
- OrderSide: Buy/Sell direction
- OrderType: Market/Limit/Stop order types

Order Lifecycle:
OrderIntent (generated by strategy)
    → Risk checks (validated by risk rules)
    → OrderExec (submitted to broker)
    → Status transitions: PENDING → ACCEPTED → FILLED/REJECTED/CANCELLED
"""

from datetime import datetime
from enum import Enum
from typing import Annotated, Optional
from pydantic import Field, field_validator
from uuid import uuid4

from shared.models.base import BaseModel, TimestampMixin, SymbolMixin


class OrderSide(str, Enum):
    """Order side enum."""
    BUY = "BUY"
    SELL = "SELL"


class OrderType(str, Enum):
    """Order type enum."""
    MARKET = "MARKET"          # Execute at current market price
    LIMIT = "LIMIT"            # Execute at specified price or better
    STOP = "STOP"              # Trigger market order when stop price reached
    STOP_LIMIT = "STOP_LIMIT"  # Trigger limit order when stop price reached


class OrderStatus(str, Enum):
    """Order status enum (lifecycle states)."""
    PENDING = "PENDING"        # Created but not yet submitted
    ACCEPTED = "ACCEPTED"      # Acknowledged by broker
    FILLED = "FILLED"          # Fully executed
    PARTIAL = "PARTIAL"        # Partially executed
    REJECTED = "REJECTED"      # Rejected by broker
    CANCELLED = "CANCELLED"    # Cancelled by user/system


class OrderIntent(BaseModel, TimestampMixin, SymbolMixin):
    """
    Order intent (pre-execution specification).

    Generated by strategy/allocation logic, before risk checks.
    Represents the desired order, not yet submitted to broker.

    Validation:
    - quantity > 0 (always positive; side determines buy/sell)
    - limit_price > 0 (if order_type is LIMIT or STOP_LIMIT)
    - stop_price > 0 (if order_type is STOP or STOP_LIMIT)

    Example:
        OrderIntent(
            symbol='AAPL',
            timestamp=datetime.now(timezone.utc),
            side=OrderSide.BUY,
            quantity=100,
            order_type=OrderType.LIMIT,
            limit_price=150.50,
            strategy_id='mean_reversion_v1'
        )
    """

    order_id: Annotated[
        str,
        Field(
            default_factory=lambda: str(uuid4()),
            min_length=1,
            max_length=100,
            description="Unique order identifier (auto-generated UUID)"
        )
    ]

    side: Annotated[
        OrderSide,
        Field(
            description="Order side: BUY or SELL"
        )
    ]

    quantity: Annotated[
        float,
        Field(
            gt=0.0,
            description="Order quantity (always positive; side determines buy/sell)"
        )
    ]

    order_type: Annotated[
        OrderType,
        Field(
            description="Order type: MARKET, LIMIT, STOP, STOP_LIMIT"
        )
    ]

    limit_price: Annotated[
        Optional[float],
        Field(
            default=None,
            gt=0.0,
            description="Limit price (required for LIMIT and STOP_LIMIT orders)"
        )
    ]

    stop_price: Annotated[
        Optional[float],
        Field(
            default=None,
            gt=0.0,
            description="Stop price (required for STOP and STOP_LIMIT orders)"
        )
    ]

    strategy_id: Annotated[
        str,
        Field(
            min_length=1,
            max_length=50,
            pattern=r'^[a-zA-Z0-9_\-]+$',
            description="Strategy that generated this order intent"
        )
    ]

    time_in_force: Annotated[
        str,
        Field(
            default="DAY",
            pattern=r'^(DAY|GTC|IOC|FOK)$',
            description="Time-in-force: DAY (day order), GTC (good-til-cancelled), IOC (immediate-or-cancel), FOK (fill-or-kill)"
        )
    ]

    metadata: Annotated[
        Optional[dict],
        Field(
            default=None,
            description="Optional metadata (e.g., parent allocation, signal reference)"
        )
    ]

    @field_validator('limit_price')
    @classmethod
    def validate_limit_price_required(cls, v: Optional[float], info) -> Optional[float]:
        """Ensure limit_price is provided for LIMIT/STOP_LIMIT orders."""
        if 'order_type' in info.data:
            order_type = info.data['order_type']
            if order_type in [OrderType.LIMIT, OrderType.STOP_LIMIT] and v is None:
                raise ValueError(f"limit_price is required for {order_type} orders")
        return v

    @field_validator('stop_price')
    @classmethod
    def validate_stop_price_required(cls, v: Optional[float], info) -> Optional[float]:
        """Ensure stop_price is provided for STOP/STOP_LIMIT orders."""
        if 'order_type' in info.data:
            order_type = info.data['order_type']
            if order_type in [OrderType.STOP, OrderType.STOP_LIMIT] and v is None:
                raise ValueError(f"stop_price is required for {order_type} orders")
        return v


class OrderExec(BaseModel, TimestampMixin, SymbolMixin):
    """
    Order execution (post-execution record).

    Returned by broker after order is submitted/filled.
    Represents the actual order state, including fills and rejections.

    Status transitions:
    - PENDING → ACCEPTED (broker acknowledged)
    - ACCEPTED → FILLED (fully executed)
    - ACCEPTED → PARTIAL (partially executed)
    - ACCEPTED → CANCELLED (user/system cancelled)
    - PENDING/ACCEPTED → REJECTED (broker rejected)

    Example:
        OrderExec(
            order_id='123e4567-e89b-12d3-a456-426614174000',
            symbol='AAPL',
            timestamp=datetime.now(timezone.utc),
            status=OrderStatus.FILLED,
            filled_quantity=100,
            average_fill_price=150.75,
            commission=1.0
        )
    """

    order_id: Annotated[
        str,
        Field(
            min_length=1,
            max_length=100,
            description="Order ID (matches OrderIntent.order_id)"
        )
    ]

    status: Annotated[
        OrderStatus,
        Field(
            description="Current order status: PENDING, ACCEPTED, FILLED, PARTIAL, REJECTED, CANCELLED"
        )
    ]

    filled_quantity: Annotated[
        float,
        Field(
            ge=0.0,
            description="Quantity filled so far (0 if not yet filled)"
        )
    ]

    remaining_quantity: Annotated[
        Optional[float],
        Field(
            default=None,
            ge=0.0,
            description="Quantity remaining (for partial fills)"
        )
    ]

    average_fill_price: Annotated[
        Optional[float],
        Field(
            default=None,
            gt=0.0,
            description="Average fill price (weighted by fill quantities)"
        )
    ]

    commission: Annotated[
        Optional[float],
        Field(
            default=0.0,
            ge=0.0,
            description="Total commission paid"
        )
    ]

    slippage: Annotated[
        Optional[float],
        Field(
            default=None,
            description="Slippage (actual fill price - expected price, can be negative if favorable)"
        )
    ]

    broker_order_id: Annotated[
        Optional[str],
        Field(
            default=None,
            max_length=100,
            description="Broker's internal order ID (e.g., IBKR order ID)"
        )
    ]

    reject_reason: Annotated[
        Optional[str],
        Field(
            default=None,
            max_length=500,
            description="Rejection reason (if status is REJECTED)"
        )
    ]

    execution_timestamp: Annotated[
        Optional[datetime],
        Field(
            default=None,
            description="Timestamp when order was filled (if status is FILLED/PARTIAL)"
        )
    ]

    metadata: Annotated[
        Optional[dict],
        Field(
            default=None,
            description="Optional metadata (e.g., exchange, venue, fill details)"
        )
    ]
