"""
Signal models for the 3-plane trading system.

Defines:
- Signal: Strategy-generated trading signal with confidence and rationale

Signals are the output of the Control Plane (strategy logic) and input to
the allocation/order generation process.

Key features:
- Direction: LONG (bullish), SHORT (bearish), FLAT (neutral/exit)
- Confidence: [0, 1] conviction level
- Rationale: Audit trail explaining why signal was generated
"""

from datetime import datetime
from enum import Enum
from typing import Annotated, Optional
from pydantic import Field

from shared.models.base import BaseModel, TimestampMixin, SymbolMixin, ConfidenceMixin


class SignalDirection(str, Enum):
    """Signal direction enum."""
    LONG = "LONG"      # Bullish signal (buy)
    SHORT = "SHORT"    # Bearish signal (sell/short)
    FLAT = "FLAT"      # Neutral signal (close position)


class Signal(BaseModel, TimestampMixin, SymbolMixin, ConfidenceMixin):
    """
    Trading signal generated by a strategy.

    Signals represent the strategy's view on a symbol:
    - Direction: LONG (buy), SHORT (sell), FLAT (exit)
    - Confidence: [0, 1] conviction level (1.0 = maximum conviction)
    - Rationale: Human-readable explanation for audit/debugging

    Signals are immutable and must include timestamp for event ordering.

    Example:
        Signal(
            symbol='AAPL',
            timestamp=datetime.now(timezone.utc),
            direction=SignalDirection.LONG,
            confidence=0.75,
            rationale='SMA crossover: 50-day > 200-day',
            strategy_id='mean_reversion_v1'
        )
    """

    direction: Annotated[
        SignalDirection,
        Field(
            description="Signal direction: LONG (buy), SHORT (sell), FLAT (exit)"
        )
    ]

    rationale: Annotated[
        str,
        Field(
            min_length=1,
            max_length=500,
            description="Human-readable explanation for why this signal was generated (audit trail)"
        )
    ]

    strategy_id: Annotated[
        str,
        Field(
            min_length=1,
            max_length=50,
            pattern=r'^[a-zA-Z0-9_\-]+$',
            description="Identifier for the strategy that generated this signal (e.g., 'mean_reversion_v1')"
        )
    ]

    target_weight: Annotated[
        Optional[float],
        Field(
            default=None,
            ge=-1.0,
            le=1.0,
            description="Optional target portfolio weight [-1, 1]. -1=max short, 0=flat, 1=max long"
        )
    ]

    stop_loss: Annotated[
        Optional[float],
        Field(
            default=None,
            gt=0.0,
            description="Optional stop-loss price (absolute price level)"
        )
    ]

    take_profit: Annotated[
        Optional[float],
        Field(
            default=None,
            gt=0.0,
            description="Optional take-profit price (absolute price level)"
        )
    ]

    metadata: Annotated[
        Optional[dict],
        Field(
            default=None,
            description="Optional strategy-specific metadata (e.g., indicators, scores)"
        )
    ]
