class IBKRExecClient:
    def __init__(self, cfg): ...
    async def connect(self): ...
    async def place(self, intent): ...
    async def cancel(self, order_id): ...
    async def poll_reports(self): ...
    def health(self): return {"connected": True, "session": 'exec'}
